name: release

on:
  push:
    tags:
      - v*.*.*

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  upload_components:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5.0.0
        with:
          fetch-depth: 0
      - uses: espressif/upload-components-ci-action@v1
        with:
          name: DCC
          version: ${{ github.ref_name }}
          namespace: zimo-elektronik
          api_token: ${{ secrets.IDF_COMPONENT_API_TOKEN }}

  # I'd have preferred a release trigger
  # release:
  #   types: [published]
  #
  # but this doesn't work.
  docs:
    uses: ./.github/workflows/docs.yml
